version: "3.1"

networks:
  todo-network:
    name: todo-network
    driver: bridge
    
services: 
  db:
    container_name: 'sql-server'
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Database!2021"
        ACCEPT_EULA: "Y"
    volumes: 
     - /var/opt/mssql/data
    networks:
     - todo-network
