spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=db_todo
    username: sa
    password: Database!2021
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

password:
  policy:
    special: 1
    lower: 1
    digit: 1
    upper: 1