CREATE TABLE dbo.tb_user
(
	id BIGINT NOT NULL,
	name VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL,
	password VARCHAR(200) NOT NULL,
);

ALTER TABLE dbo.tb_user ADD CONSTRAINT PK_5
	PRIMARY KEY (id);

CREATE SEQUENCE sq_user START WITH 1 INCREMENT BY 1 ;
CREATE UNIQUE NONCLUSTERED INDEX tb_user_email_Idx ON dbo.tb_user (email);

